### ISSUE TITLE
Rename to `heroicons`

### ISSUE THREAD

**Issue by jclusso** [jclusso/heroicons#3]
As discussed in https://github.com/bharget/heroicon/issues/37, we're going to switch this gem to become `heroicons` on Rubygems. Thanks to @marckohlbrugge for getting @chunlea to pass over the existing gem! 

@chunlea, you'll need to go to https://rubygems.org/gems/heroicons/owners and add myself `jclusso`. Once you do that I can get started on this.

**Comment by chunlea** [comment]
Done! Invite sent
